### ISSUE TITLE
Regarding Codalab submission

### ISSUE THREAD

**Issue by 009deep** [a-nagrani/VoxSRC2020#1]
I am seeing for last year's open competition, leaderboard show result of last submission and not the best one.

- Will leaderboard be considered on basis of best of 5 or last of 5? Also, in case of best of 5 any specific action will be needed from participant?

Also, I am only seeing 2019 competition so far. Is 2020 server open now? If not, what is expected date (as per website it would be early August)?

**Comment by joonson** [comment]
We have released the test data some time ago, but we were able to open the evaluation server at the same time due to some server issues with Codalab. We are working to resolve this, and the server should be live soon.

**Comment by 009deep** [comment]
Thanks @joonson for response. 

Where can I find test set for 2020?

**Comment by joonson** [comment]
@009deep It's on the [challenge website](http://www.robots.ox.ac.uk/~vgg/data/voxceleb/competition2020.html)

**Comment by 009deep** [comment]
Thanks @joonson . 

Also regarding submissions, will the last result count or the best  one?

**Comment by joonson** [comment]
It's the best one

**Comment by 009deep** [comment]
Thanks. 

@joonson I  requested  participation  24 hours  ago, I received e-mail saying  my I  am granted  participation 12 or so hours ago   and now I received e-mail saying my permission revoked.

I haven't even submitted anything yet. Is server still under  testing and permission is revoked for all participants? Or there is additional step  to be taken to participate?

Thanks.

**Comment by joonson** [comment]
Hi @009deep , I think that your account has been revoked as it was signed up using `@gmail.com` address. The website states that

`We have an evaluation server to allow teams to benchmark their performance on a blind test set over the course of (and even after) the evaluation period. Submissions will be made through the CodaLab website. The challenge is open to all, we only ask that you use an institutional email to register.`

Could you sign up again using a company or university email address? If this is not feasible, please let us know.

**Comment by 009deep** [comment]
I see. Even though I created my account using my company id in profile I added my personal,I've updated my profile with company id. 

Please let me know if that works.

**Comment by joonson** [comment]
Your account should be usable now!

**Comment by 009deep** [comment]
Yep, I did. Thank you so much.
