### ISSUE TITLE
Regarding  Technical Paper Submissin Deadline

### ISSUE THREAD

**Issue by 009deep** [a-nagrani/VoxSRC2020#3]
What is  deadline for technical paper submission? [Here](http://www.robots.ox.ac.uk/~vgg/data/voxceleb/competition2020.html#dates) it says miid-October, but what is exact date?
Last day for  competition submission  in  Oct 15. Will there be another week/couple of days after that?

**Comment by joonson** [comment]
It will be around Oct 20, but we will announce the exact date soon.

**Comment by 009deep** [comment]
I  can see it's updated  to 26ht  Oct. thanks.
