### ISSUE TITLE
Can I submit technical paper for only one track?

### ISSUE THREAD

**Issue by 009deep** [a-nagrani/VoxSRC2020#4]
Even though I  am participating in multiple tracks, I want to highlight  technical details only on track 2 as that has been my focus and most of my research result, model training was along that line. 
Can  I choose to include details on only  one track in technical paper?

**Comment by joonson** [comment]
Yes, this is fine. In fact, the winner of the last year's challenge has done this -- see https://arxiv.org/abs/1910.12592

**Comment by 009deep** [comment]
Thanks. Yes, I can share similar details once I have  all the data but due to gpu and time constraint I won't have similar result on similar architectures for both the tracks.
