### ISSUE TITLE
Where can I find VoxSRC challenge details on Interspeech website?

### ISSUE THREAD

**Issue by 009deep** [a-nagrani/VoxSRC2020#5]
I am  trying  to find  details  of this  challenge on  [Interspeech challenge page](http://www.interspeech2020.org/Program/Special_Sessions_and_Challenge/) . But I am unable to find it. Where can I find details  of this challenge on Interspeech website?

**Comment by joonson** [comment]
It can be found [here](http://www.interspeech2020.org/Program/Workshops/)

**Comment by 009deep** [comment]
thanks
